### ISSUE TITLE
PipeScript Should Support Attribute Based Composition

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PipeScript#6]
One of the core facets of PipeScript as a language is the support for Attribute Based Composition.

Attribute Based Composition is when you use attributes to describe behavior, rather than write all of the code.

Attributes can be used to compose scripts in a few different places:

* [ ] #7 (this will perform operations with that variable)
* [ ] #9 (enabling modifications to scripts)
* [ ] #7 (enabling custom modifications to a ```[ScriptBlock]````)
* [ ] #16 (to support a transpiled object pipeline)
